name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest  
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './eventmanagement/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd eventmanagement
          npm ci --only=production
          npm install

      - name: Build application
        run: |
          cd eventmanagement
          NODE_ENV=production npm run build
          
      - name: Optimize build output
        run: |
          cd eventmanagement/dist
          
          # Remove all source maps and development files
          find . -name "*.map" -delete
          find . -name "*.txt" -delete
          find . -name ".DS_Store" -delete
          find . -name "*.log" -delete
          
          # Remove any development-only files
          find . -name "*.dev.*" -delete
          find . -name "*.development.*" -delete
          
          # Clean up empty directories
          find . -type d -empty -delete
          
          # Compress large text files if any
          find . -name "*.js" -size +100k -exec echo "Large JS file: {}" \;
          find . -name "*.css" -size +50k -exec echo "Large CSS file: {}" \;
          
          # Final count and size check
          FILE_COUNT=$(find . -type f | wc -l)
          TOTAL_SIZE=$(du -sh . | cut -f1)
          echo "Final file count: $FILE_COUNT"
          echo "Total size: $TOTAL_SIZE"
          
          # Fail if too many files (Azure limit is around 20,000)
          if [ $FILE_COUNT -gt 15000 ]; then
            echo "ERROR: Too many files ($FILE_COUNT). Azure Static Web Apps limit exceeded."
            exit 1
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_07F5F4E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./eventmanagement"
          api_location: ""
          output_location: "dist"
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_07F5F4E00 }}
          action: "close"

