name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest  
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './eventmanagement/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd eventmanagement
          npm install

      - name: Build application
        run: |
          cd eventmanagement
          npm run build
          
      - name: Clean up build artifacts
        run: |
          cd eventmanagement/dist
          # Remove source maps and other unnecessary files
          find . -name "*.map" -delete
          find . -name "*.txt" -delete
          find . -name ".DS_Store" -delete
          # Remove empty directories
          find . -type d -empty -delete
          # Count files for debugging
          echo "Total files in dist: $(find . -type f | wc -l)"
          echo "Largest files:"
          find . -type f -exec ls -la {} + | sort -k5 -nr | head -10
          echo "File breakdown by type:"
          find . -type f | sed 's/.*\.//' | sort | uniq -c | sort -nr

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_07F5F4E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./eventmanagement"
          api_location: ""
          output_location: "dist"
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_07F5F4E00 }}
          action: "close"

