name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest  
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './eventmanagement/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd eventmanagement
          npm ci --only=production
          npm install

      - name: Build application
        run: |
          cd eventmanagement
          NODE_ENV=production npm run build
          
      - name: Debug and optimize build output
        run: |
          cd eventmanagement/dist
          
          echo "=== BEFORE CLEANUP ==="
          echo "Files before cleanup:"
          find . -type f | head -20
          echo "Total files: $(find . -type f | wc -l)"
          echo "Total size: $(du -sh . | cut -f1)"
          
          # Remove ALL unnecessary files more aggressively
          rm -rf node_modules/ 2>/dev/null || true
          
          # Remove all config and development files
          find . -name "package*.json" -delete 2>/dev/null || true
          find . -name "yarn.lock" -delete 2>/dev/null || true
          find . -name "tsconfig*.json" -delete 2>/dev/null || true
          find . -name ".npmrc" -delete 2>/dev/null || true
          find . -name ".yarnrc*" -delete 2>/dev/null || true
          find . -name "vite.config.*" -delete 2>/dev/null || true
          find . -name "tailwind.config.*" -delete 2>/dev/null || true
          find . -name "postcss.config.*" -delete 2>/dev/null || true
          find . -name "*.config.*" -delete 2>/dev/null || true
          
          # Remove ALL source maps and development files
          find . -name "*.map" -delete 2>/dev/null || true
          find . -name "*.txt" -delete 2>/dev/null || true
          find . -name ".DS_Store" -delete 2>/dev/null || true
          find . -name "*.log" -delete 2>/dev/null || true
          find . -name "*.dev.*" -delete 2>/dev/null || true
          find . -name "*.development.*" -delete 2>/dev/null || true
          
          # Remove TypeScript declaration files
          find . -name "*.d.ts" -delete 2>/dev/null || true
          
          # Remove test files
          find . -name "*.test.*" -delete 2>/dev/null || true
          find . -name "*.spec.*" -delete 2>/dev/null || true
          find . -name "__tests__" -type d -exec rm -rf {} + 2>/dev/null || true
          
          # Remove documentation files
          find . -name "README*" -delete 2>/dev/null || true
          find . -name "CHANGELOG*" -delete 2>/dev/null || true
          find . -name "LICENSE*" -delete 2>/dev/null || true
          find . -name "*.md" -delete 2>/dev/null || true
          
          # Remove hidden files and directories (except .well-known)
          find . -name ".*" -not -path "./.well-known*" -delete 2>/dev/null || true
          
          # Remove any remaining vendor/library files that aren't needed
          find . -name "src" -type d -exec rm -rf {} + 2>/dev/null || true
          find . -name "lib" -type d -exec rm -rf {} + 2>/dev/null || true
          find . -name "dist" -type d -not -path "." -exec rm -rf {} + 2>/dev/null || true
          
          # Clean up empty directories recursively
          find . -type d -empty -delete 2>/dev/null || true
          find . -type d -empty -delete 2>/dev/null || true  # Run twice to catch nested empty dirs
          
          echo "=== AFTER CLEANUP ==="
          echo "Remaining files:"
          find . -type f -ls
          
          FILE_COUNT=$(find . -type f | wc -l)
          TOTAL_SIZE=$(du -sh . | cut -f1)
          echo "Final file count: $FILE_COUNT"
          echo "Total size: $TOTAL_SIZE"
          
          # List the actual files that remain
          echo "=== FILE LIST ==="
          find . -type f | sort
          
          # Check if we still have too many files
          if [ $FILE_COUNT -gt 50 ]; then
            echo "ERROR: Still too many files ($FILE_COUNT)"
            echo "Listing files by size:"
            find . -type f -exec ls -lah {} \; | sort -k5 -hr | head -20
            exit 1
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_07F5F4E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./eventmanagement"
          api_location: ""
          output_location: "dist"
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_RIVER_07F5F4E00 }}
          action: "close"